In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import pandas_datareader
import datetime
import pandas_datareader.data as web

In [7]:
start=datetime.datetime(2012, 1, 1)
end=datetime.datetime(2019, 12, 31)
api_key="mYnpdhz7HnGbCoT5qz6-"
delta=web.DataReader('DAL', 'quandl', start, end, access_key=api_key)

/home/ronet/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: the 'access_key' keyword is deprecated, use 'api_key' instead
  after removing the cwd from sys.path.

In [8]:
delta

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,55.31,55.475,53.96,54.26,6630294.0,0.0,1.0,55.310000,55.475000,53.960000,54.260000,6630294.0
2018-03-26,54.57,55.275,54.07,55.06,5704464.0,0.0,1.0,54.570000,55.275000,54.070000,55.060000,5704464.0
2018-03-23,54.78,55.210,53.84,53.90,7265632.0,0.0,1.0,54.780000,55.210000,53.840000,53.900000,7265632.0
2018-03-22,55.50,56.000,54.63,54.67,6577056.0,0.0,1.0,55.500000,56.000000,54.630000,54.670000,6577056.0
2018-03-21,55.49,56.360,54.75,55.95,9159784.0,0.0,1.0,55.490000,56.360000,54.750000,55.950000,9159784.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2012-01-09,8.34,8.500,8.26,8.28,9015700.0,0.0,1.0,7.903337,8.054960,7.827526,7.846479,9015700.0
2012-01-06,8.26,8.430,8.24,8.32,6683300.0,0.0,1.0,7.827526,7.988625,7.808573,7.884384,6683300.0
2012-01-05,8.03,8.350,7.87,8.33,10509800.0,0.0,1.0,7.609568,7.912814,7.457945,7.893861,10509800.0
2012-01-04,8.03,8.140,7.83,8.01,7412900.0,0.0,1.0,7.609568,7.713809,7.420040,7.590615,7412900.0
2012-01-03,8.23,8.300,8.02,8.04,7093200.0,0.0,1.0,7.799097,7.865431,7.600092,7.619044,7093200.0

In [9]:
web.DataReader('GOOG', 'quandl', start, end, access_key=api_key)

/home/ronet/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: the 'access_key' keyword is deprecated, use 'api_key' instead
  """Entry point for launching an IPython kernel.

,Open,High,Low,Close,Volume,ExDividend,SplitRatio,AdjOpen,AdjHigh,AdjLow,AdjClose,AdjVolume
Date,,,,,,,,,,,,
2018-03-27,1063.000,1064.84,996.92,1005.10,3029471.0,0.0,1.0,1063.000,1064.84,996.92,1005.10,3029471.0
2018-03-26,1046.000,1055.63,1008.40,1053.21,2558385.0,0.0,1.0,1046.000,1055.63,1008.40,1053.21,2558385.0
2018-03-23,1047.030,1063.36,1021.22,1021.57,2113497.0,0.0,1.0,1047.030,1063.36,1021.22,1021.57,2113497.0
2018-03-22,1081.880,1082.90,1045.91,1049.08,2580374.0,0.0,1.0,1081.880,1082.90,1045.91,1049.08,2580374.0
2018-03-21,1092.740,1106.30,1085.15,1090.88,1640709.0,0.0,1.0,1092.740,1106.30,1085.15,1090.88,1640709.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-04-02,565.106,604.83,562.19,567.00,146700.0,0.0,1.0,565.106,604.83,562.19,567.00,146700.0
2014-04-01,558.710,568.45,558.71,567.16,7900.0,0.0,1.0,558.710,568.45,558.71,567.16,7900.0
2014-03-31,566.890,567.00,556.93,556.97,10800.0,0.0,1.0,566.890,567.00,556.93,556.97,10800.0
2014-03-28,561.200,566.43,558.67,559.99,41100.0,0.0,1.0,561.200,566.43,558.67,559.99,41100.0
2014-03-27,568.000,568.00,552.92,558.46,13100.0,0.0,1.0,568.000,568.00,552.92,558.46,13100.0